# Generated by Django 2.1 on 2018-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aryan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aryan_name', models.CharField(max_length=100)),
            ],
        ),
    ]
