# Generated by Django 2.1 on 2018-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_aryan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='aryan',
        ),
    ]
